### ISSUE TITLE
Does PRCLBot work in private repos within orgs?

### ISSUE THREAD

**Issue by rajgrailed** [prclbot/prclbot-test#1]
@mukul13 Great product idea! We were looking forward to using this at work.

Do you know if it supports repositories private to an org? I can't see the code so I couldn't tell.

When I install changelogg to our repo, I can only see the `master` branch in the drop-down list (our repo doesn't even have a `master` branch). It doesn't show other branches to which we have merged PRs that follow the conventional commit guidelines.

Here is a screenshot:

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/50594022/93918506-725d2b00-fcda-11ea-9da9-4ac4b3eb1fbe.png">

Confusingly, it also shows a `Link to install Github App from Marketplace` section even though clearly it's already connected to the repo I want.

**Comment by mukul13** [comment]
Hi @rajgrailed, Thanks for using Changelogg!

Yes, it supports private repositories too. You can control repository access (public/private from app settings). To see the reflected changes, please login and logout again.
<img width="794" alt="Screenshot 2020-09-23 at 12 00 10 AM" src="https://user-images.githubusercontent.com/8403230/93922631-d1995a80-fd2f-11ea-802f-0fb022af4416.png"> 

Currently, it does not import/create changelog from the past commits and PR. After app installation only, PRs merged to any branch in any repo will be automatically reflected to the Changelogg dashboard and in Changelog.md. It will also create above branch filters automatically

It currently defaults to the master branch which is definitely an issue I will be working on to fix this week [[link](https://github.com/prclbot/prclbot-test/issues/2)]

Please let me know if the above info helps in solving the issue or it still persists.
Thank you!

**Comment by rajgrailed** [comment]
> After app installation only, PRs merged to any branch in any repo will be automatically reflected the Changelogg dashboard and in Changelog.md. It will also create above branch filters automatically

Thanks for the reply @mukul13. I can confirm that the app had been installed _before_ we merged the PRs with the conventional template format in the PR description and we still didn't see the branches to which those PRs were merged.

Confirmed also that we could see in the configuration that Changelogg _did_ have permissions to our repo.

Is there anything else you can think of that might be going wrong?

-----

Thanks for filing the issue to fix the `master` entry showing up.

**Comment by mukul13** [comment]
Got it. After checking the server logs, I found an issue in parsing/fetching commits data which might be causing this. I have released a fix for it just now. If it's possible, can you please verify?

(To check and verify: you can simply merge a PR with conventional commits to check the working status)

**Comment by rajgrailed** [comment]
ah yeah, it works now! Gold! Thanks so much for your help.

**Comment by mukul13** [comment]
Awesome @rajgrailed! Sounds great! 
Do let me know if you or your team have any change/feature requests for changelogg 😄

**Comment by rajgrailed** [comment]
Will do, Mukul. Thanks!
